stages:
  download:
    cmd: uv run python trainer.py --config-name config stage=download
    deps:
      - src/training/data/download_data.py
    params:
      - params.yaml:
        - data.competition_name
        - data.raw_dir
        - data.overwrite
    outs:
      - data/raw/train.csv
      # - data/raw/test.csv
  
  train:
    cmd: uv run python trainer.py --config-name config stage=train
    deps:
      - src/training/train.py
      - src/training/features/preprocess.py
      - src/training/features/transformers.py
      - src/training/pipeline.py
      - src/training/evaluate.py
      - data/raw/train.csv
    params:
      - params.yaml:
          - training.test_size
          - training.random_state
          - model.name
          - model.C
          - model.max_iter
          - model.n_estimators    
          - model.max_depth      
    # outs:
    #   - data/processed/:
    #       persist: true
    #   - models/${model.name}_pipeline.pkl:
    #       persist: true
    # metrics:
    #   - reports/${model.name}_metrics.json:
    #       cache: false
    outs:
      - data/processed/:
          persist: true
      - models/:
          persist: true
    metrics:
      - reports/:
          persist: true
          cache: false
    

